### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by Bobtro** [emilyb7/HTML-templating-with-Google-Apps-Script#1]
Emily,
Thank you for your speedy reply!! 
This is still not working for me - I click on Display and a name is not posted. 
Also - are the latest Code.gs and template files posted?
Thanks

**Comment by emilyb7** [comment]
Hi @Bobtro,

This should be the correct link to the latest version of the app: https://script.google.com/macros/s/AKfycbwh4HDtHNnmWB8DURyePbKwlBF3_Q2I8DTBEt2qHP4IQRaIUqE/exec

The expected behaviour is as follows:

1. Select a user name from the drop down list

<img width="404" alt="screen shot 2017-12-27 at 19 59 08" src="https://user-images.githubusercontent.com/17532458/34391889-7e02fb46-eb40-11e7-927a-a626e6762800.png">

2. Click "display"

The result should look like this:

<img width="495" alt="screen shot 2017-12-27 at 20 00 04" src="https://user-images.githubusercontent.com/17532458/34391906-97f5022e-eb40-11e7-89bf-664122aab646.png">

That's all it does.

If you're seeing different behaviour, please do let me know. As you know, I've had some problems with the deployed version. A screenshot would be very useful.

And yes, the code you see on GitHub is the same as is currently deployed to the app.

**Comment by Bobtro** [comment]
It should do exactly as I expect it to do - but not yet! Maybe there is a Chrome setting I should tweek?

**Comment by Bobtro** [comment]
Now works ok on my machine - after changing the published version!! Now to try and use it further!

**Comment by emilyb7** [comment]
Ok great :) well thanks for helping me discover the problem with running the app!
I hope everything works ok now, but don't hesitate to let me know if there's anything else that needs to be improved. In the meantime, let's close this issue?

**Comment by Bobtro** [comment]
I wrote too soon - the first time through it showed the result for Emily and Ines but not Sohil. The second time I deployed the app it didn't work for any name at all.

**Comment by emilyb7** [comment]
Sorry I can't be more helpful but the app is working fine for me. If you're keen to really understand how everything works, I would recommend creating a new version with your own spreadsheet, script and data (if you haven't done that already). The error handling in my original code can probably be improved. Try and figure out whether it's a problem within the Google sheets setup, or a problem with getting the data from GitHub. You can use `logger.log` to your advantage here.  Let me know how you get on!

**Comment by Bobtro** [comment]
Thanks for replying - I would like to see this work for 2 reasons - 1) just to solve it! and 2) I might be able to use this construction in my project. 
Here is the console error message which pops up when I select a name and hit Display - it doesn't mean much to me - any thoughts? 
Uncaught Error: Request failed for https://api.github.com/users/iteles returned code 403. Truncated server response: {"message":"API rate limit exceeded for 107.178.195.133. (But here's the good news: Authenticated requests get a higher rate limit. Check out the d... (use muteHttpExceptions option to examine full response).
 at getImage (Code:22) (WebApp Template) dd47ead5-df90-4d47-a3c3-06d9bf8d8f18
 at getData (Code:37) (WebApp Template) dd47ead5-df90-4d47-a3c3-06d9bf8d8f18

**Comment by emilyb7** [comment]
yes, that one I can explain, and the problem's not directly related to my app, but to the way the GitHub API works.

Have a look at: https://developer.github.com/v3/rate_limit/

The github API won't let a single user make too many requests to their API. That explains the random behaviour you've been seeing. It's not _you_ that's calling their API, but Google's servers. Google of course have a lot of servers, but also a lot of other users, so sometimes it will work and sometimes it won't.

You could have a look at authenticating your requests - this should be ok as long as you don't store your access token anywhere that's publicly accessible (check out this other tutorial I wrote here that explains it in a bit more detail https://github.com/emilyb7/workshop-APIs).

But if the project you're hoping to work on doesn't rely on an API, then maybe you just don't need to worry about this :)

**Comment by Bobtro** [comment]
Thank you again - I'll get rid of any GitHub reference - ie the logo then all should be well!!
